name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # setiap hari
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: NaufalArkaan
          outputs: |
            dist/pacman-contribution-graph.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
